# Site settings
title: Emanuel Canepa Jimenez
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Emanuel Canepa Jimenez
user_description: Mi nombre es Emanuel Canepa Jimenez, soy estudiante universitario actual, con experiencia previa en organización de archivos en desarrollo urbano. Trabajé en tiendas de conveniencia, donde tuve que desarrollar mis habilidades en idiomas
user_title: Estudiante Universitario
email: 250300516@ucaribe.edu.mx
# twitter_username: @bonepoi
instagram_username: @bonepoi
facebook_username: emanuel.canepa
linkedin_username: emanuel.canepa66
github_username:  Emanuel61209
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

